# -*- coding: utf-8 -*-
"""Brasileirão

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11_Wmy9VEsbqkxvTDXKVu9l3tWbxNVRqN
"""

from google.colab import drive
drive.mount ('/content/drive')

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import classification_report

# Carregar os dados do arquivo CSV
caminho = '/content/drive/MyDrive/Cópia de brasileirão 2024 rodada 23 - brasileirão 2024.csv'
df = pd.read_csv(caminho)
# Definindo colunas relevantes para a analise
relevant_columns = ['time_mandante', 'time_visitante', 'gols_mandante', 'gols_visitante', 'resultado']
df_model = df[relevant_columns].copy()
df_model.dropna(inplace=True)

# Pegando os ultimos 5 resultados dos times
def ultimos_resultados(times, ultimos_jogos=5):

    jogos_recentes = df[(df['time_mandante'] == times) | (df['time_visitante'] == times)]
    jogos_recentes = jogos_recentes.tail(ultimos_jogos)

    vitorias = 0
    empates = 0
    derrotas = 0
    gols_feitos = 0
    gols_sofridos = 0

    for _, jogos in jogos_recentes.iterrows():
        if jogos['time_mandante'] == times:
            if jogos['gols_mandante'] > jogos['gols_visitante']:
                vitorias += 1
            elif jogos['gols_mandante'] == jogos['gols_visitante']:
                empates += 1
            else:
                derrotas += 1
            gols_feitos += jogos['gols_mandante']
            gols_sofridos += jogos['gols_visitante']
        else:
            if jogos['gols_visitante'] > jogos['gols_mandante']:
                vitorias += 1
            elif jogos['gols_visitante'] == jogos['gols_mandante']:
                empates += 1
            else:
                derrotas += 1
            gols_feitos += jogos['gols_visitante']
            gols_sofridos += jogos['gols_mandante']

    return vitorias, empates, derrotas, gols_feitos, gols_sofridos

df_model['time_mandante_wins'], df_model['time_mandante_draws'], df_model['time_mandante_losses'], df_model['time_mandante_goals_scored'], df_model['time_mandante_goals_conceded'] = zip(*df_model['time_mandante'].apply(ultimos_resultados))
df_model['time_visitante_wins'], df_model['time_visitante_draws'], df_model['time_visitante_losses'], df_model['time_visitante_goals_scored'], df_model['time_visitante_goals_conceded'] = zip(*df_model['time_visitante'].apply(ultimos_resultados))

le_teams = LabelEncoder()
df_model['time_mandante'] = le_teams.fit_transform(df_model['time_mandante'])
df_model['time_visitante'] = le_teams.transform(df_model['time_visitante'])


le_result = LabelEncoder()
df_model['resultado'] = le_result.fit_transform(df_model['resultado'])
X = df_model[['time_mandante', 'time_visitante', 'gols_mandante', 'gols_visitante',
                'time_mandante_wins', 'time_mandante_draws', 'time_mandante_losses', 'time_mandante_goals_scored', 'time_mandante_goals_conceded',
                'time_visitante_wins', 'time_visitante_draws', 'time_visitante_losses', 'time_visitante_goals_scored', 'time_visitante_goals_conceded']]
y = df_model['resultado']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

model = RandomForestClassifier(random_state=42, class_weight='balanced')
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
print(classification_report(y_test, y_pred, target_names=le_result.classes_))

# Definir jogos da rodada
rodada = [
    ('Atlético-GO', 'Juventude'),
    ('Palmeiras', 'Cuiabá-MT'),
    ('Atlético-MG', 'Fluminense'),
    ('EC Bahia', 'Botafogo'),
    ('Fortaleza', 'Corinthians'),
    ('Criciúma EC', 'Grêmio'),
    ('São Paulo', 'EC Vitória'),
    ('Internacional', 'Cruzeiro'),
    ('Flamengo', 'RB Bragantino'),
    ('Vasco da Gama', 'Athletico-PR')
]

# Previsões para a rodada inteira,
for mandante, visitante in rodada:
    # Codificar os times
    time_casa = le_teams.transform([mandante])[0]
    time_fora = le_teams.transform([visitante])[0]

    # Usar o desempenho recente dos times\n",
    mandante_recent_wins, mandante_recent_draws, mandante_recent_losses, mandante_recent_goals_scored, mandante_recent_goals_conceded = ultimos_resultados(mandante)
    visitante_recent_wins, visitante_recent_draws, visitante_recent_losses, visitante_recent_goals_scored, visitante_recent_goals_conceded = ultimos_resultados(visitante)

    input_data = pd.DataFrame({
        'time_mandante': [time_casa],
        'time_visitante': [time_fora],
        'gols_mandante': [mandante_recent_goals_scored],
        'gols_visitante': [visitante_recent_goals_scored],
        'time_mandante_wins': [mandante_recent_wins],
        'time_mandante_draws': [mandante_recent_draws],
        'time_mandante_losses': [mandante_recent_losses],
        'time_mandante_goals_scored': [mandante_recent_goals_scored],
        'time_mandante_goals_conceded': [mandante_recent_goals_conceded],
        'time_visitante_wins': [visitante_recent_wins],
        'time_visitante_draws': [visitante_recent_draws],
        'time_visitante_losses': [visitante_recent_losses],
        'time_visitante_goals_scored': [visitante_recent_goals_scored],
        'time_visitante_goals_conceded': [visitante_recent_goals_conceded]
    })

    # Prever o resultado
    predicted_result = model.predict(input_data)
    predicted_result_label = le_result.inverse_transform(predicted_result)[0]

    print(f'{mandante} x {visitante}: {predicted_result_label}')

df.head()